[package]
name = "type-layout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO: enable overflow checks in release builds?

[dependencies]

[dev-dependencies]
insta = "1.0"
